Change to SimpleAjax extension
MetaModels/attribute_levensthein pull request #2
Opened 2017-02-02 19:01 UTC by richardhj

2017-02-06 17:42 UTC, discordier commented
I am undecided if we want to add a nother dependency here for the endpoint.
For Contao 4 we will then remove it again (as we will use a proper controller with a custom route then).

@MetaModels/team what do you think about this?

2017-03-27 21:34 UTC, richardhj commented
RTM

2017-05-09 05:58 UTC, zonky2 commented
..have we discussed this on the 28.02.2017 at the MM-call?

2017-05-30 19:41 UTC, zonky2 commented
we use the PR from @richardhj after any small changes...

[MM-call 30.05.2017]

2017-05-30 19:46 UTC, richardhj commented on src/MetaModels/Filter/Setting/LevenstheinAjax.php
> -        $input = \Input::getInstance();
Backport

2017-05-30 19:47 UTC, richardhj commented on src/MetaModels/Filter/Setting/LevenstheinSearchSetting.php
> -                    "mm_lv_search.php",
Introduce service for retrieving ajax endpoint

2017-07-25 19:48 UTC, discordier requested changes
As discussed on Mumble on 2017-07-25, we want to get rid of the exit expressions.
@richardhj will update his simple ajax to also accept Response instances and then this is RTM.

2017-08-08 15:50 UTC, discordier commented
This now needs a dependency on `symfony/http-foundation`.

2017-08-08 17:36 UTC, richardhj commented
This is now a dependency of simple-ajax.

2017-08-15 22:55 UTC, discordier commented
Yet, it also is one of this repository now, as we create a new response instance here

2018-01-23 07:22 UTC, zonky2 commented
@discordier & @richardhj - was ist den nun aus dem PR geworden?!?

2018-01-23 07:26 UTC, richardhj commented
Gute Frage.
Ich denke wir müssen nichts mehr mergen hier.
v2.1. hat jetzt eine eigene Route bekommen btw.

2018-01-23 07:29 UTC, zonky2 commented
@discordier bitte Statement dazu - bitte fixen/mergen oder schließen...

2018-02-05 20:27 UTC, discordier commented
@richardhj In essence this means we won't fix it for MM 2.0 at all?

2018-03-03 07:12 UTC, zonky2 commented
@richardhj @discordier ja was den nun?!?!?

2018-03-03 07:20 UTC, closed without merging